sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    endpoint: oss-cn-fuzhou.aliyuncs.com
    access-key-id: LTAI5t77vRWeUCsTPJTWEinw
    access-key-secret: 30aXJVk5yqb8G2oWruby0h13X4MLfx
    bucket-name: gpvi-pic